#theme: minima
locale: en-CA
title: Delaney's Portfolio
description: "Portfolio of projects in design, manufacturing, and craftsmanship"
baseurl: ""
url: https://theirishwolf.github.io/
logo: /assets/images/WolfProfile.png

# Personal
author: "Delaney Fitzpatrick"
email: delaneyfitzpatrick77@gmail.com
github_username: TheIrishWolf

plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
# - jekyll-include-cache

# Build settings
#remote_theme: mmistakes/so-simple-theme
markdown: kramdown
permalink: pretty

# Navigation links
header_pages:
  - index.html
  - projects.md
  - about.md

# Collections
collections:
  images:
    output: true
    permalink: /assets/images/:name/
  projects:
    output: true
    permalink: /_projects/:name/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # project defaults
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: project
      comments: true
      share: true
