remote_theme: jekyll-theme-so-simple
locale: en-CAD 
title: "Delaney's Portfolio"
description: "Portfolio of projects in design, manufacturing, and craftsmanship"
baseurl: ""
url: "https://TheIrishWolf.github.io"
logo: _images/WolfProfile.png

# Personal
author: TheIrishWolf
email: delaneyfitzpatrick77@gmail.com
github_username: TheIrishWolf

plugins:
- jekyll-remote-theme
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
# - jekyll-include-cache

# Build settings
markdown: kramdown
permalink: pretty

# Navigation links
header_pages:
  - index.md
  - projects.md
  - about.md

# Collections for projects
collections:
  images:
    output: true
    permalink: /_images/:name/
  projects:
    output: true
    permalink: /_projects/:name/
#/:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # project defaults
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: project
      comments: true
      share: true


 # Footer Links
 footer_links:
  - title: GitHub
    url: https://github.com/TheIrishWolf
    icon: fab fa-github-square
  - title: Feed
#    url: atom.xml
    icon: fas fa-rss-square
